-- require('autoclose').setup({
--     options = {
--         disable_when_touch = true,
--         pair_spaces = true
--     },
--     keys = {
--         [">"] = { pair = "<>", close = false, escape = false }
--     }
-- })
